library(fda)
library(roahd)
library(coda)
library(devtools)
library(latex2exp)
library(calculus)
library(freqdom)
library(freqdom.fda)
library(ggplot2)
library(tidyverse)
library(geigen)
library(fdapace)
library(progress)
library(multiwave)

rm(list=ls())
graphics.off()
cat("\014")